create table public.expenses (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount > 0),
  category text not null check (
    category in ('Ludmila', 'Gasto comida', 'Varios', 'Boludez')
  ),
  created_at timestamptz not null default now()
);

alter table public.expenses enable row level security;

create policy "Allow anonymous reads"
on public.expenses
for select
to anon
using (true);

create policy "Allow anonymous inserts"
on public.expenses
for insert
to anon
with check (
  amount > 0
  and category in ('Ludmila', 'Gasto comida', 'Varios', 'Boludez')
);

create policy "Allow anonymous deletes"
on public.expenses
for delete
to anon
using (true);
